spring:
  liquibase:
    enabled: true
#    change-log: classpath:db.changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/test_app_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.springframework: ERROR
    com.lobanov.financeservice: TRACE
